
#include <fstream>
#include <thread>
#include <chrono>
#include <D3D11.h>
#include <wrl/client.h>
#include <functional>
#include <stack>
#include <map>
#include <filesystem>
#include <array>
#include <regex>
#define NOCOCOO std::enable_if_t
#define NOCOCOOO std::is_pointer_v
#define NOCOCOOOO std::is_lvalue_reference_v
#define NOCOCOOOOO std::is_same_v
#define NOCOCOOOOOO std::add_pointer_t
#define NOCOCOOOOOOO std::remove_reference_t
#define OOOOOOOOO template <typename CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO>
#define OOOOOOOOOo std::optional
using NOCOOOOO = OOOOOOOOOo<unsigned char>;
#define CONOOOOOOOOOOOOOOOOOOOOOOOOO std::vector
using NOCOOOOOoooooooo = CONOOOOOOOOOOOOOOOOOOOOOOOOO<NOCOOOOO>;
#define CONOOOO namespace
#define CONOOOOO inline
#define CONOOOOOO int
#define CONOOOOOOO void
#define CONOOOOOOOO nullptr
#define CONOOOOOOOOO unsigned long long
#define CONOOOOOOOOOO public
#define CONOOOOOOOOOOO class
#define CONOOOOOOOOOOOO static_cast
#define CONOOOOOOOOOOOOO std::string
#define CONOOOOOOOOOOOOOO long long
#define CONOOOOOOOOOOOOOOO return
#define CONOOOOOOOOOOOOOOOO 4
#define CONOOOOOOOOOOOOOOOOO else
#define CONOOOOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO char
#define CONOOOOOOOOOOOOOOOOOOO unsigned char
#define CONOOOOOOOOOOOOOOOOOOOO IMAGE_DOS_HEADER
#define CONOOOOOOOOOOOOOOOOOOOOO continue
#define CONOOOOOOOOOOOOOOOOOOOOOO if
#define CONOOOOOOOOOOOOOOOOOOOOOOO for
#define CONOOOOOOOOOOOOOOOOOOOOOOOO UINT8_MAX
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOO true
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOO false
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOO CONOOOOOOOOO
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO bool
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 1
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 0x10
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO const
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 0
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO std::istringstream
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO IMAGE_NT_HEADERS
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO break
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO OOOOOOOOOo
#define CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO while
#define TELLUSER printf
#define DOG6 std::vector
#define DOG7 std::string
#define DOG8 return
#define DOG9 for
#define DOG10 char

DOG6<DOG7> CNOOOOOOOOOO() {
	DOG6<DOG7> DOGOOOOO;
	DOG9(DOG10 DOGOOOOODOGOOOOO = 'a'; DOGOOOOODOGOOOOO <= 'z'; ++DOGOOOOODOGOOOOO) {
		DOG7 DOGOOOOODOGOOOOODOGOOOOODOGOOOOO;
		DOGOOOOODOGOOOOODOGOOOOODOGOOOOO.push_back(DOGOOOOODOGOOOOO);
		DOGOOOOO.push_back(DOGOOOOODOGOOOOODOGOOOOODOGOOOOO);
	}
	DOG9(DOG10 DOGOOOOODOGOOOOO = 'A'; DOGOOOOODOGOOOOO <= 'Z'; ++DOGOOOOODOGOOOOO) {
		DOG7 DOGOOOOODOGOOOOODOGOOOOODOGOOOOO;
		DOGOOOOODOGOOOOODOGOOOOODOGOOOOO.push_back(DOGOOOOODOGOOOOO);
		DOGOOOOO.push_back(DOGOOOOODOGOOOOODOGOOOOODOGOOOOO);
	}
	DOG9(DOG10 DOGOOOOODOGOOOOO = '0'; DOGOOOOODOGOOOOO <= '9'; ++DOGOOOOODOGOOOOO) {
		DOG7 DOGOOOOODOGOOOOODOGOOOOODOGOOOOO;
		DOGOOOOODOGOOOOODOGOOOOODOGOOOOO.push_back(DOGOOOOODOGOOOOO);
		DOGOOOOO.push_back(DOGOOOOODOGOOOOODOGOOOOODOGOOOOO);
	}
	DOGOOOOO.push_back("?");
	DOGOOOOO.push_back(" ");
	DOG8 DOGOOOOO;
}

DOG7 CNOOOOOOOOOOCNOOOOOOOOOO(DOG7 CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO) {
	DOG7 COCOC;
	DOG6<DOG7> CNOOOOOOOOOOCNOOOOOOOOOO = CNOOOOOOOOOO();
#define co unsigned __int64
	co CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO = 0;
	while (CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO < CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO.length()) {
		if (CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO[CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO] == 'C') {
			co CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO = CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO + 1;
			co NOOOOOOOOOOCNOOOOOOOOOOCNOOOOO = CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO.find('N', CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO);
			if (NOOOOOOOOOOCNOOOOOOOOOOCNOOOOO != DOG7::npos) {
				DOG7 OOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOO = CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO.substr(CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO, NOOOOOOOOOOCNOOOOOOOOOOCNOOOOO - CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO);
				DOG9(int i = 0; i < CNOOOOOOOOOOCNOOOOOOOOOO.size(); i++) {

					if (std::to_string(i) == OOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOO) {
						COCOC += CNOOOOOOOOOOCNOOOOOOOOOO[i];
						continue;
					}
				}
				CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO = NOOOOOOOOOOCNOOOOOOOOOOCNOOOOO + 1;
			}
			else {
				break;
			}
		}
		else {
			CNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOOCNOOOOOOOOOO += 1;
		}
	}
	DOG8 COCOC;
}
//#CONOOOOOOOOOOOOOOsdOOOOOOOOOO
CONOOOO nonono_sun{
	CONOOOOO CONOOOOOO CONOOOOOOOOOOOOOOOOOOOOODFDFDFFDOOOOOOOOOO{};
	CONOOOOOOOOOOO CONOOOOOOOOOOOOOOsdOOOOOOOOOO {
	CONOOOOOOOOOO:
		CONOOOOOOOOOOOOOOsdOOOOOOOOOO(CONOOOOOOO * CONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO = CONOOOOOOOO) : CONOOOOOOOOOOOOOOOOOOOOODFDFDFFDOOOOOCOOOOO(CONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {}
		CONOOOOOOOOOOOOOOsdOOOOOOOOOO(CONOOOOOOOOO CONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO) : CONOOOOOOOOOOOOOOsdOOOOOOOOOO((CONOOOOOOO*)CONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {}
	CONOOOOOOOOOO:
		OOOOOOOOO NOCOCOO<NOCOCOOO<CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO>, CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO> color() { CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOO<CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO>(CONOOOOOOOOOOOOOOOOOOOOODFDFDFFDOOOOOCOOOOO); }
		OOOOOOOOO NOCOCOO<NOCOCOOOO<CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO>, CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO> color() { CONOOOOOOOOOOOOOOO* CONOOOOOOOOOOOO<NOCOCOOOOOO<NOCOCOOOOOOO<CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO>>>(CONOOOOOOOOOOOOOOOOOOOOODFDFDFFDOOOOOCOOOOO); }
		OOOOOOOOO NOCOCOO<NOCOCOOOOO<CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO, CONOOOOOOOOO>, CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO> color() { CONOOOOOOOOOOOOOOO(CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOO)CONOOOOOOOOOOOOOOOOOOOOODFDFDFFDOOOOOCOOOOO; }
	CONOOOOOOOOOO:
		CONOOOOOOOOOOOOOOsdOOOOOOOOOO heat(CONOOOOOOOOO CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) { CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOsdOOOOOOOOOO(color<CONOOOOOOOOO>() + CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO); }
		CONOOOOOOOOOOOOOOsdOOOOOOOOOO cold(CONOOOOOOOOO CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) { CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOsdOOOOOOOOOO(color<CONOOOOOOOOO>() - CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO); }
		CONOOOOOOOOOOOOOOsdOOOOOOOOOO FREEZE() { CONOOOOOOOOOOOOOOO heat(color<CONOOOOOO&>()).heat(CONOOOOOOOOOOOOOOOO); }
	CONOOOOOOOOOO:
		CONOOOOOOO * CONOOOOOOOOOOOOOOOOOOOOODFDFDFFDOOOOOCOOOOO{};
	};
	CONOOOOOOOOOOO CONOOOOOOOOOOOOOOOFFDGOOOOOOOOO {
	CONOOOOOOOOOO:
		CONOOOOOOOOOOOOOOOFFDGOOOOOOOOO(CONOOOOOOOOOOOOO CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = "") : CONOOOOOOOOcOOOcOOOOOOOOOOO(GetModuleHandleA(CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.empty() ? NULL : CONOOOOOCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.data())) {
			CONOOOOOOOOcOOOOOOOOOOOOOO = CONOOOOOOOOcOOOcOOOOOOOOOOO.heat(CONOOOOOOOOcOOOcOOOOOOOOOOO.color<CONOOOOOOOOOOOOOOOOOOOO*>()->e_lfanew).color<CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO*>()->OptionalHeader.SizeOfImage;
		}
	CONOOOOOOOOOO:
		CONOOOOOOOOOOOOOOsdOOOOOOOOOO CONOOOOOOOOcOOOcOOOOOOOOOOO{};
		CONOOOOOOOOOOOOOO CONOOOOOOOOcOOOOOOOOOOOOOO{};
	};
	CONOOOOO NOCOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOGOCONOOO(CONOOOOOOOOOOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO) {
		CONOOOOOOOOOOOOOOOOOOOOOO(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO >= 'a' && OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO <= 'f') CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOO<CONOOOOOOOOOOOOOOOOOOO>(CONOOOOOOOOOOOO<CONOOOOOO>(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO) - 87);
		CONOOOOOOOOOOOOOOOOOOOOOO(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO >= 'A' && OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO <= 'F') CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOO<CONOOOOOOOOOOOOOOOOOOO>(CONOOOOOOOOOOOO<CONOOOOOO>(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO) - 55);
		CONOOOOOOOOOOOOOOOOOOOOOO(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO >= '0' && OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO <= '9') CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOO<CONOOOOOOOOOOOOOOOOOOO>(CONOOOOOOOOOOOO<CONOOOOOO>(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOCONOOO) - 48);
		CONOOOOOOOOOOOOOOO {};
	}
	CONOOOOO NOCOOOOOoooooooo OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCONOOO(CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO CONOOOOOOOOOOOOO& OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCCOCNCOOO) {
		NOCOOOOOoooooooo OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOCOGOCCOCNCOOO{};
		CONOOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO{}; OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO != OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCCOCNCOOO.size() - CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO; ++OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO) {
			CONOOOOOOOOOOOOOOOOOOOOOO(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCCOCNCOOO[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO] == ' ') CONOOOOOOOOOOOOOOOOOOOOO;
			CONOOOOOOOOOOOOOOOOOOOOOO(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCCOCNCOOO[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO] != '?') {
				CONOOOOOOOOOOOOOOOOOOOOOO(NOCOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCONCOOO{ OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOGOCONOOO(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCCOCNCOOO[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO]) }; OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCONCOOO) {
					CONOOOOOOOOOOOOOOOOOOOOOO(NOCOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCOCNCOOO{ OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOGOCONOOO(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCCOCNCOOO[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO + CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO]) }; OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCOCNCOOO) {
						OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOCOGOCCOCNCOOO.emplace_back(CONOOOOOOOOOOOO<CONOOOOOOOOOOOOOOOOOOO>((*OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCONCOOO * CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) + *OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCOCNCOOO));
					}
				}
			}
			CONOOOOOOOOOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOCOGOCCOCNCOOO.push_back({});
		}
		CONOOOOOOOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOCOGOCCOCNCOOO;
	}
	CONOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOsdOOOOOnoOOOOO(CONOOOOOOOOOOOOOOOOOOO* CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnCoOOOOO, OOOOOOOOOo<CONOOOOOOOOOOOOOOOOOOO> CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO* CONOOOOOOOOOOOOOOOOOOOOOOOOCOOOOOOOOOOOOOO, CONOOOOOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOCOCCCOOOOOOOOOOOOO) {
		CONOOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO{}; OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO != CONOOOOOOOOOOOOOOOOOOOOOOOOCOCCCOOOOOOOOOOOOO; ++OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO) {
			CONOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOOOOOOOOOOOOCOOOOOOOOOOOOOO[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO] && *CONOOOOOOOOOOOOOOOOOOOOOOOOCOOOOOOOOOOOOOO[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO] != CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnCoOOOOO[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO]) {
				CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOOOO;
			}
		}
		CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOOO;
	}
	CONOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOO<CONOOOOOOOOO> CONOOOOOOOOOOOOOOOFFDDFGOOOOOOOOO(CONOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOFFDDFGDFOOOOOOOOO, CONOOOOOOOOOOOOOOOFFDGOOOOOOOOO CONOOOOOOOOOOOOOOOFGOOOOOOOOO = {}) {
		CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO NOCOOOOOoooooooo NOCOOOOOoooooooo{ OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCONOOO(CONOOOOOOOOOOOOOOOFFDDFGDFOOOOOOOOO) };
		CONOOOOOOOOOOOOOOOOOOOOOOOOO<CONOOOOOOOOO> CONOOOOOOOOOOOOOOsdcDXCSCCvOCOOOOnCoOOOOO{};
		CONOOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO{}; OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO != CONOOOOOOOOOOOOOOOFGOOOOOOOOO.CONOOOOOOOOcOOOOOOOOOOOOOO - NOCOOOOOoooooooo.size(); ++OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO) {
			CONOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOOsdOOOOOnoOOOOO(CONOOOOOOOOOOOOOOOFGOOOOOOOOO.CONOOOOOOOOcOOOcOOOOOOOOOOO.heat(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO).color<CONOOOOOOOOOOOOOOOOOOO*>(), NOCOOOOOoooooooo.data(), NOCOOOOOoooooooo.size())) {
				CONOOOOOOOOOOOOOOsdcDXCSCCvOCOOOOnCoOOOOO.push_back(CONOOOOOOOOOOOOOOOFGOOOOOOOOO.CONOOOOOOOOcOOOcOOOOOOOOOOO.heat(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO).color<CONOOOOOOOOO>());
			}
		}
		CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOsdcDXCSCCvOCOOOOnCoOOOOO;
	}
	CONOOOOO CONOOOOOOOOOOOOOOsdOOOOOOOOOO UUU(CONOOOOOOOOOOOOOOOOOO* CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO222, CONOOOOOOOOOOOOOOOOOO* CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO, CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO COCOCOOCCOOCC = CONOOOOOOOOOOOOOOOOOOOOOOOOOOO, CONOOOOOOOOOOOOOOOFFDGOOOOOOOOO CONOOOOOOOOOOOOOOOFGOOOOOOOOO = {}) {
		CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO NOCOOOOOoooooooo NOCOOOOOoooooooo{ OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCONOOO(CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO) };
		CONOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOO{ CONOOOOOOOOOOOO<CONOOOOOOOOOOOOOO>(NOCOOOOOoooooooo.size()) }, CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOOOOOOOOOOO{ CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOO - CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO }, CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOROOOORRROOOOOO[CONOOOOOOOOOOOOOOOOOOOOOOOO + CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO]{}, CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOROOOOOOOOOO{ -CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO };
		CONOOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO{ CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOOOOOOOOOOO - CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO }; OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO >= CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO; --OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO) {
			CONOOOOOOOOOOOOOOOOOOOOOO(!NOCOOOOOoooooooo[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO]) {
				CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOO = CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOOOOOOOOOOO - OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO;
				CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOROOOOOOOOOO = OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO;
				CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
			}
		}
		CONOOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO{}; OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO <= CONOOOOOOOOOOOOOOOOOOOOOOOO; ++OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO) CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOROOOORRROOOOOO[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO] = CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOO;
		CONOOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOO OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO{ CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOROOOOOOOOOO + CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO }; OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO != CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOOOOOOOOOOO; ++OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO) CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOROOOORRROOOOOO[*NOCOOOOOoooooooo[OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO]] = CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOOOOOOOOOOO - OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCCOOGOCCOCNCOOO;
		CONOOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnoOOOOO{}; CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnoOOOOO != CONOOOOOOOOOOOOOOOFGOOOOOOOOO.CONOOOOOOOOcOOOOOOOOOOOOOO - CONOOOOOOOOOOOO<CONOOOOOOOOOOOOOO>(NOCOOOOOoooooooo.size()); ) {
			CONOOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOsdcDXCSCvOOOOOnoOOOOO{ CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOOOOOOOOOOO }; CONOOOOOOOOOOOOOOsdcDXCSCvOOOOOnoOOOOO >= CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO; --CONOOOOOOOOOOOOOOsdcDXCSCvOOOOOnoOOOOO) {
				CONOOOOOOOOOOOOOOOOOOOOOO(NOCOOOOOoooooooo[CONOOOOOOOOOOOOOOsdcDXCSCvOOOOOnoOOOOO].has_value() && *CONOOOOOOOOOOOOOOOFGOOOOOOOOO.CONOOOOOOOOcOOOcOOOOOOOOOOO.heat(CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnoOOOOO + CONOOOOOOOOOOOOOOsdcDXCSCvOOOOOnoOOOOO).color<CONOOOOOOOOOOOOOOOOOOO*>() != NOCOOOOOoooooooo[CONOOOOOOOOOOOOOOsdcDXCSCvOOOOOnoOOOOO].value()) {
					CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnoOOOOO += CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOROOOORRROOOOOO[*CONOOOOOOOOOOOOOOOFGOOOOOOOOO.CONOOOOOOOOcOOOcOOOOOOOOOOO.heat(CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnoOOOOO + CONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOOOOOOOOOOOOOCONOOOOOOOOOOOOOROOOOOOOOOOOO).color<CONOOOOOOOOOOOOOOOOOOO*>()];
					CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
				}
				CONOOOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOOsdcDXCSCvOOOOOnoOOOOO == CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {
					CONOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOOOFGOOOOOOOOO.CONOOOOOOOOcOOOcOOOOOOOOOOO.heat(CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnoOOOOO).color<CONOOOOOOOOO>()) {
						TELLUSER("found %s\n", CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO222);
						CONOOOOOOOOOOOOOOOOOOOOODFDFDFFDOOOOOOOOOO++;
						CONOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOFGOOOOOOOOO.CONOOOOOOOOcOOOcOOOOOOOOOOO.heat(CONOOOOOOOOOOOOOOsdcDXCSCCvOOOOOnoOOOOO).color<CONOOOOOOOOO>();
					}
					CONOOOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOO CONOOOOOOOO;
				}
			}
		}
		CONOOOOOOOOOOOOOOO CONOOOOOOOO;
	}
	CONOOOOO CONOOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOcccOOOOOO(CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO CONOOOOOOOOOOOOO& OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCCOCNCOOO) {
		CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO COCOCOOCCOOC(OCONOOOOOOOOOOCONOOOOOOOOOOOOOOOOOCOOGOCCOCNCOOO);
		CONOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOOODOOOOOOOO;
		CONOOOOOO NOINONN{};
		CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO(COCOCOOCCOOC >> CONOOOOOOOOOOOOOOOOOOOOOOOOOODOOOOOOOO) {
			CONOOOOOOOOOOOOOOOOOOOOOO(CONOOOOOOOOOOOOOOOOOOOOOOOOOODOOOOOOOO == "?") {
				CONOOOOOOOOOOOOOOO NOINONN;
			}
			NOINONN++;
		}
		CONOOOOOOOOOOOOOOO - CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO;
	}

	CONOOOOO CONOOOOOOOOOOOOOOsdOOOOOOOOOO CONOOOOOOOOOOOOOOsdcDXCSvOOOOOnoOOOOO(CONOOOOOOOOOOOOOOOOOO* CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO2, CONOOOOOOOOOOOOOOOOOO* CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO) {
		CONOOOOOOOOOOOOOOO UUU(CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO2, CNOOOOOOOOOOCNOOOOOOOOOO(CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO).c_str()).heat(CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOOcccOOOOOO(CNOOOOOOOOOOCNOOOOOOOOOO(CONOOOOOOOOOOOOOOsdcDSvOOOOOnoOOOOO))).FREEZE();
	}
}
CONOOOO sun_nonoonon{
	CONOOOOO CONOOOOOOO UU(CONOOOOOOO * CONOOOOOOOOOOOOOOOFFDDFGDFOOOOOOOOO, CONOOOOOO opcode, CONOOOOOOOOOOOOOOOOOOOOOOOOOOOO CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOO) {
		memset(CONOOOOOOOOOOOOOOOFFDDFGDFOOOOOOOOO, opcode, CONOOOOOOOOOOOOOOOOOOOOOOOOOOOOO);
	}
}